---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# DEPMEP

<!-- badges: start -->
<!-- badges: end -->

DEPMEP is a Shiny app to support the Massachusetts Department of Environmental Protection's "Maximum Extent Practicable" 
guidelines for planning culvert and bridge upgrades. It provides a web map of streams and road-stream crossings in Massachusetts, with scores for each stream segment and each crossing. The scores can be help determine whether the cost 
of a culvert or bridge upgrade fits within DEP's "maximum extent practicable" regulations. For background and detail, see guidance document "Meeting the Massachusetts Stream Crossing Standards to the Maximum Extent Practicable" (currently in draft form, and not yet posted).

This web app is currently under development and uses test data, some of which has been randomly generated. A mature version is
planned for release in late summer 2023.
